# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WineMe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WineMe
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'WineMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WineMe-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WineMe-tvOS

  target 'WineMe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
